### ISSUE TITLE
final markbot

### ISSUE THREAD

**Issue by guer0125** [guer0125/saas-website#2]
Hi there,

markbot requirements:

1.index.html
line 77: stray tag `footer`

2.tour.html
line 239: stray tag `footer`

3.All page content must be contained by landmarks... **I have tried different things and can't get passed it**

4.The skip-link target should not exist and be focusable...try adding `tabindex="0"` to the matching `id` i **did tried adding `tabindex="0"`, my understanding is that i have to add this to the other page where the id is**

Thank you

@muxlowc

**Comment by muxlowc** [comment]
@guer0125 

1) you shouldnt be closing your` <body>` tag until the very end - even after your footer. `<body>` does not mean the same thing as `<main>`. The body tag basically just means "Your code goes here" - so literally any code you want to appear on your site should be inside of your body tag

2) The above should hopefully solve #2 question

3) You need to assign roles - ie your <header> should have role="banner" https://learn-the-web.algonquindesign.ca/topics/accessibility-cheat-sheet/#wai-aria-landmark-roles
You also need to make sure your code looks kind of like the below:

```
<header role="banner">
<nav role="navigation">
....
</header>
<main role="main">
<section></section>
<section></section>
...
</main>
<footer role="contentinfo">
..
</footer>
```
(so your landmarks (roles) shouldn't be buried inside a bunch of code - they need to be at the highest level of code, if that makes sense?)

4) Pretty much everywhere you have an id="" it will need a tabindex="0" - these basically just mean that that section with the tabindex will be "tab-able"
For example:
`<main role="main" id="main" tabindex="0">`

Also, for your skip-links:
```
  <ul class="skip-links">
    <li><a href="#main">Jump to main content</a></li>
    <li><a href="#nav">Jump to navigation</a></li>
  </ul>
```
where it says "href="#nav" and "href="#main" - you need to have a correspnding ID for each of those hashtags - so you need to add id="nav" on your `<nav>`, and id="main" to your `<main>`
Remember that the href="#main" means, "when you click this link, it will go to whatever tag has the ID on THIS page = id="main" " ---seems like you're missing your ID tags, which might also be where that error is coming from

**Comment by guer0125** [comment]
Hi,

it seems like im done with markbot, the only errors showing now are the price.html which i didn't do.

now, i have a problem with `embed`. i've watched the videos but it doesn't seem to work the way i want it to.

so i have on my `index.html`

<div class="unit xs-1 m-1 l-1-3 gutter **embed embed-3by2**">
          <img class="img-flex chop **embed-item**" src="images/hand-shake.jpg" alt="" role="presentation">
        </div>

so i got that number with h:427px / w:626px = 68%
`embed-3by2` seems the closest at 66%
it looks good when medium and small window, but it's stretched in Large window.

i have this same problem with my banner for Sign-up on my large window. 

thank you

**Comment by muxlowc** [comment]
@guer0125 so it seems like there was something on embed-item that was messing around with it.. try this:

go to your modules.css, find .embed-item, and remove:   min-height: 100%; 

I think that should work?

**Comment by guer0125** [comment]
yes, thank you
